### PR TITLE
feat: `createAwsCognitoOAuthConfig()`

### LINKED ISSUE #310: AWS Cognito provider?
Is there any interest in adding an AWS Cognito provider? I recently used kv-oauth to interact with a Cognito user pool and would be happy to clean it up and contribute. I could also include some CDK for a basic Cognito setup if that would be helpful.

### PR DESCRIPTION
**Pull request by gdtroszak**
Adds the configuration for a Cognito User Pool provider.

This assumes users have their user pool app client properly configured. Namely, it needs to have a client secret generated, have the appropriate callback URLs registered, and support the AuthorizationCodeGrant flow. 

Resolves #310

#### Signed Out
Screenshot 2024-03-06 at 11 00 58 AM

#### Signed In
Screenshot 2024-03-06 at 11 01 18 AM

### CODE REVIEW

**Review by iuioiua — COMMENTED** [review]
I think we should call this AWS Cognito. I.e. `createAwsCognitoOAuthConfig()`, `AWS_COGNITO_CLIENT_ID`, etc. WDYT?

**Comment by gdtroszak** [comment]
> I think we should call this AWS Cognito. I.e. `createAwsCognitoOAuthConfig()`, `AWS_COGNITO_CLIENT_ID`, etc. WDYT?

Works for me. I'll ping you when I make the change.

**Comment by gdtroszak** [comment]
@iuioiua Naming updated!

**Review by iuioiua — APPROVED** [review]
LGTM! Thank you for this. Much appreciated.

**Pull request merged**
