### PR TITLE
feat: slack client

### PR DESCRIPTION
**Pull request by lino-levan**
~~This is a "classic" slack app instead of a "new" slack app, but "new" slack apps aren't really oauth so probably out-of-scope for this module.~~

We decided to go with the "new" slack oauth option for now. Please make some noise if you need the old one for some reason.

### CODE REVIEW

**Comment by iuioiua** [comment]
Thanks! Are you able to update this PRs initial comment and add Slack to the list in the README?

**Comment by iuioiua** [comment]
Has this been tested? My initial tests show that the `redirectUri` property is also needed.

**Comment by lino-levan** [comment]
Should be fine. Tested classic but didn't get around to testing this.

The docs state:
> When you ask for scopes, you also need to tell Slack where to send your temporary authorization code afterward. Include a redirect_uri parameter in the URL above. The redirect_uri is where Slack will send the user back to, along with the temporary authorization code, once the user okays your app. The redirect_uri must use HTTPS.

but right under that they also state:
> Alternatively, you can configure a Redirect URL in the App Management page under OAuth & Permissions. A Redirect URL must also use HTTPS.

so I think it's optional.

source: https://api.slack.com/authentication/oauth-v2#asking

**Review by iuioiua — APPROVED** [review]
I tested this, and it's working. LGTM! Thank you.

**Pull request merged**
