### PR TITLE
fix: set cookies with global path

### PR DESCRIPTION
**Pull request by lino-levan**
I will often make the login path something deeply nested (i.e. `/api/user/login/github`) and having the cookies be limited to that deeply nested path seems more like a bug than a feature. This PR should make the cookies available for the entire host.

### CODE REVIEW

**Comment by iuioiua** [comment]
This brings up a good point. I created #32 on what I'd like to have. Would you like to tackle that issue in this PR? It overlaps with your requirement.

**Comment by lino-levan** [comment]
Sure, that makes sense.

**Comment by lino-levan** [comment]
(do not merge yet, we need to think of a better way of handling secure cookies)

**Comment by lino-levan** [comment]
Sure, sorry. `localhost` isn't a "Secure" origin in the context of cookies. My thinking is that we disable `Secure: true` as well as `__Host` if the request is coming from localhost. Does that seem reasonable?

**Comment by iuioiua** [comment]
Yep, lets make it conditional - dependent on the request.

**Comment by lino-levan** [comment]
Also, somewhat unrelatedly, we don't pass the request object into sign-in. If we want this behavior, we would have to. Not a problem, since this is obviously not a stable interface yet, but just letting you know.

**Comment by iuioiua** [comment]
I just tested it on my local machine, and it worked. I believe Chrome regards `http://localhost` as a secure origin. Actually, let's make it conditional on `Secure` so no one runs into any issues.

**Comment by lino-levan** [comment]
Closing this PR because I don't want to deal with merge conflicts, but will open one right now with what was added.

**Pull request closed without merging**
