### PR TITLE
feat: `createPatreonOAuth2Client()`

### PR DESCRIPTION
**Pull request by j3lte**
- Adding support for [Patreon](https://www.patreon.com/)

### CODE REVIEW

**Comment by lino-levan** [comment]
I also don't believe that Patreon supports PKCE.

**Review by iuioiua — APPROVED** [review]
LGTM! However, please confirm whether this has been tested from sign-in to sign-out.

**Comment by j3lte** [comment]
> I also don't believe that Patreon supports PKCE.

Correct. See [this comment](https://github.com/denoland/deno_kv_oauth/pull/95#issuecomment-1595942261) to get a resolution on how to move forward with whether or not we would support clients that do not support PKCE

> LGTM! However, please confirm whether this has been tested from sign-in to sign-out.

Yes, I have also tested this against a created Patreon app. I followed the steps that are described in [https://www.patreon.com/portal/registration/register-clients](https://www.patreon.com/portal/registration/register-clients) and I get a valid accessToken

**Comment by iuioiua** [comment]
If Patreon doesn't support PKCE, then how is it that this new function is working?

**Comment by lino-levan** [comment]
I don't understand how this could work if it doesn't support PKCE. I'll try to get this running locally to verify. If it does work, this opens up some questions on Twitch's side.

**Comment by j3lte** [comment]
OK now I am confused... I'll set up a working example when I get back home (say an hour) and show you. I got it working and returned a valid sessionToken. I'll add an API call to it that will retrieve account data from Patreon.

**Comment by j3lte** [comment]
Here you go:

https://github.com/denoland/deno_kv_oauth/assets/2557568/b29826e1-a7a5-494b-854d-586dd04b2475

I added a bit of code to test the authToken:

```typescript
const oauth2Client = createPatreonOAuth2Client({
  redirectUri: "http://localhost:8000/callback",
  defaults: {
    scope: "identity identity[email]"
  }
});

async function indexHandler(request: Request) {
  const sessionId = await getSessionId(request);
  const data = sessionId !== null
    ? {
      accessToken: await getSessionAccessToken(oauth2Client, sessionId),
      action: "out",
    }
    : {
      accessToken: "undefined",
      action: "in",
    };

  let body = `
    <p>Your access token: ${data.accessToken}</p>
    <p><a href="/sign${data.action}">Sign ${data.action}</a></p>
  `;

  if (sessionId !== null) {
    const url = encodeURI("https://www.patreon.com/api/oauth2/v2/identity?fields[user]=about,created,email,first_name,full_name,image_url,last_name,social_connections,thumb_url,url,vanity");
    const me = await fetch(url, {
      headers: {
        authorization: `Bearer ${data.accessToken}`,
      },
    }).then((res) => res.json());

    body += `
      <p>Showing: <b>data.attributes.full_name</b>: ${me.data.attributes.full_name}</p>
    `;
  }

  return new Response(body, {
    headers: { "content-type": "text/html; charset=utf-8" },
  });
}
```

**Comment by iuioiua** [comment]
Yeah, cool! My previous comment said differently: the workflow only works if the provider supports PKCE. Otherwise, we'd be looking at a false positive, which I don't believe is true. Either way, thanks again, @j3lte!

**Pull request merged**
