### PR TITLE
BREAKING: `getSessionKey()`

### PR DESCRIPTION
**Pull request by iuioiua**
This change replaces `sessionId: string` with `sessionKey: [number, string]`. This functionality is a prerequisite for future work that ensures KV is kept clean.

Towards #148
CC @adoublef

### CODE REVIEW

**Comment by kt3k** [comment]
The code looks good to me.

I think this change breaks the existing user's apps. Do you have any plan about how to communicate with the existing users?

**Comment by kt3k** [comment]
(Just FYI there are uuid alternatives which are time sortable by lexical order https://deno.land/x/ulid@v0.2.0 https://github.com/novemberborn/ksuid )

**Comment by iuioiua** [comment]
> (Just FYI there are uuid alternatives which are time sortable by lexical order https://deno.land/x/ulid@v0.2.0 https://github.com/novemberborn/ksuid )

Omg... If I understand correctly, that nullifies this entire PR 🤣 😮

**Comment by adoublef** [comment]
Ah that is a good, find @kt3k I hadn't orginally thought of just changing the uuid to a sortable one, I presume @iuioiua you have looked into using those instead?

**Comment by iuioiua** [comment]
Yeah, great find. I'm writing a superseding PR that uses ULIDs instead.

**Comment by adoublef** [comment]
@iuioiua ah great, great thank you for the efforts too

**Comment by iuioiua** [comment]
Closing in favour of #151.

**Pull request closed without merging**
