### PR TITLE
docs: add Cheetah and Hono web framework examples

### PR DESCRIPTION
**Pull request by adoublef**

### CODE REVIEW

**Comment by iuioiua** [comment]
Can you please run `deno fmt` and then `deno task ok`?

**Comment by iuioiua** [comment]
Also, can you please link to the source code so other devs know how to make this module work with the respective frameworks?

**Comment by adoublef** [comment]
Should be all ok now, the links direct to the playground to match the other demos

**Review by iuioiua — APPROVED** [review]
Sorry for the delay. LGTM! I'd recommend adding a "Source" link to each demo that links to the playground. Thank you, Rahim!

**Comment by iuioiua** [comment]
This closes #146.

**Pull request merged**
