### PR TITLE
feat: `createNotionOAuth2Client()`

### PR DESCRIPTION
**Pull request by j3lte**
- Adding a client for [Notion](https://www.notion.so/)

### CODE REVIEW

**Comment by j3lte** [comment]
Checked the other PRs that were merged, I have taken the same steps (Add `@$VERSION` and doing `deno fmt`)

**Comment by lino-levan** [comment]
I don't think notion supports PKCE but I'm not 100% sure. Not mentioned in their docs anywhere.

**Review by iuioiua — APPROVED** [review]
LGTM! Can you please confirm whether this has been fully tested?

**Comment by j3lte** [comment]
@iuioiua 

> I don't think notion supports PKCE but I'm not 100% sure. Not mentioned in their docs anywhere.

I have checked, it does not seem to be the case. Is this an issue? If this is an issue, then we should skip both this one as well as #98, as both do not seem to support PKCE. If not, we might just add a table to the README in this form:

### Adapters
| Adapter | Supports [PKCE](https://oauth.net/2/pkce/)? |
| - | - |
| [Google](https://deno.land/x/deno_kv_oauth/mod.ts?s=createGoogleOAuth2Client) | Yes |
| [Notion](https://deno.land/x/deno_kv_oauth/mod.ts?s=createNotionOAuth2Client) | **No** |
| ... | ... |


> LGTM! Can you please confirm whether this has been fully tested?

Yes! Tested this against my own created Notion App, I get an access token

**Comment by iuioiua** [comment]
See https://github.com/denoland/deno_kv_oauth/pull/98#issuecomment-1596281106

**Pull request merged**
