### PR TITLE
BREAKING: do not store tokens

### PR DESCRIPTION
**Pull request by iuioiua**
This change removes all database storage and retrieval of tokens. This includes the removal of `getSessionAccessToken()` and other minor changes. Looking at some web apps, I couldn't find a single instance of the access token being used outside of the OAuth callback handler. So now, the access token is only provided in the callback handler. The developer can implement their own mechanisms for storing the access token, but it shouldn't be required in most cases.

These changes have the added benefit of:
- Reducing the module's API surface area
- Making the module more lightweight
- Improving the understandability of the module as it requires less moving parts
- Slight performance improvements where tokens were previously either stored or retrieved
- Being more secure as tokens are no longer stored at all and cannot be stolen

Note: We may need to revert _some_ of this functionality if token revocation is eventually implemented in the underlying x/oauth2_client module.

### CODE REVIEW

**Comment by jollytoad** [comment]
I don't use the access token, but I do use the id token, supplied by a fork of oauth2_client, which does get stored with other tokens, but I use getTokens from core to get it.

**Comment by iuioiua** [comment]
@jollytoad, are you able to share your implementation with me?

**Comment by jollytoad** [comment]
yes I was just looking, on tablet atm, so it's taking me a while...

https://github.com/jollytoad/deno_ahx_hub/blob/main/auth/handler.ts#L59

what I actually do is get the id token in the callback, verify it and then store the claims, so could live without tokens in kv if the handleCallback returned all tokens that would have been stored

**Comment by iuioiua** [comment]
Actually, that's a good point... If we're removing access token storage, we should move to expose the entire token object in the `handleCallback()` return object.

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
