### PR TITLE
BREAKING: remove Fresh plugin

### LINKED ISSUE #191: todo: remove Fresh plugin
The Fresh plugin will now live within the Fresh repo (https://github.com/denoland/fresh/issues/1733).

@mbhrznr will take this one.

### PR DESCRIPTION
**Pull request by mbhrznr**
closes #191.  

this is the pendant to https://github.com/denoland/fresh/pull/1774.

### CODE REVIEW

**Review by iuioiua — CHANGES_REQUESTED** [review]
Let's link to Fresh's docs on how to to get started. Maybe we could use a quote block? I'm open to whatever.

**Comment by iuioiua** [comment]
Not to self: merge this one the Fresh plugin is in the latest Fresh release.

**Review by iuioiua — APPROVED** [review]
LGTM! Thank you for this. I'll merge once the latest stable version of Fresh has the plugin.

**Comment by iuioiua** [comment]
Actually, I'll merge this now and instead cut a release after Fresh.

**Comment by miguelrk** [comment]
Should the fresh plugin be added again after being removed in `fresh@1.5.1` by https://github.com/denoland/fresh/pull/1910 ?

**Comment by iuioiua** [comment]
> Should the fresh plugin be added again after being removed in `fresh@1.5.1` by [denoland/fresh#1910](https://github.com/denoland/fresh/pull/1910) ?

We added a [Get Started with Fresh](https://github.com/denoland/deno_kv_oauth#get-started-with-fresh) README section in #265. PTAL and let me know if you have any questions 🙂

**Pull request merged**
